root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/slashbot"
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go", "html"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
